spring:
  datasource:
    username: clientPOC_2
    url: jdbc:h2:mem:data;DATABASE_TO_LOWER=TRUE
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      settings.web-allow-others: true

server.port: 8089
management.endpoints.web.exposure.include: "*"
config.value: clientPOC_2 default

---

spring:
  config.activate.on-profile: dev

server.port: 8089
management.endpoints.web.exposure.include: "*"
config.value: clientPOC_2 dev

---

spring:
  config.activate.on-profile: qa
  datasource:
    username: clientPOC_2-qa
    url: jdbc:h2:mem:data;DATABASE_TO_LOWER=TRUE
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      settings.web-allow-others: true

server.port: 8089
management.endpoints.web.exposure.include: "*"
config.value: clientPOC_2 qa