spring:
  config.activate.on-profile: dev
  datasource:
    username: dev
    url: jdbc:h2:mem:data;DATABASE_TO_LOWER=TRUE
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      settings.web-allow-others: true

---

spring:
  config.activate.on-profile: qa
  datasource:
    username: qa
    url: jdbc:h2:mem:data;DATABASE_TO_LOWER=TRUE
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      settings.web-allow-others: true