spring:
  config.activate.on-profile: dev
  datasource:
    username: dev1-sub
    url: jdbc:h2:mem:data;DATABASE_TO_LOWER=TRUE
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      settings.web-allow-others: true

server.port: 8088
management.endpoints.web.exposure.include: "*"
config.value: dev1 file sub

