spring:
  profiles.active: local
  # application.name: The RAD Notifications microservice - ${spring.profiles.active}
  config:
    import:
      - classpath:context-path.yml
      - classpath:cors.yml
      - classpath:kubernetes.yml
      - classpath:logging.yml
      - classpath:persistence.yml
      - classpath:persistence-local.yml
      - classpath:retry.yml
      - classpath:security.yml
      - classpath:swagger.yml

server.port: 8081
