spring:
  config.activate.on-profile: 'local'
  datasource:
    username: sa
    url: jdbc:h2:mem:data;DATABASE_TO_LOWER=TRUE
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      settings.web-allow-others: true

---

spring:
  config:
    activate:
      on-profile: 'mssql'

  datasource:
    url: jdbc:sqlserver://localhost;databaseName=RadLocalNotifications
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: yourStrong(!)Password

