spring:
  config.activate.on-profile: 'dev | qa | stage | prod'
  lifecycle.timeout-per-shutdown-phase: 20s

server:
  shutdown: graceful
  forward-headers-strategy: NATIVE

management.endpoint.health:
  enabled: true
  show-details: always
  probes.enabled: true
