logging.level.root: info

---

spring.config.activate.on-profile: '!dev & !qa & !stage & !prod'

logging:
  level:
    com.pwc.rad.notifications: debug
  pattern:
    console: "%clr(${LOG_LEVEL_PATTERN:}%-5p) %clr(:){faint} %m %clr(---){faint} %clr([%logger{0}.%M:%L]){cyan}%n%wEx"
